### ISSUE TITLE
Testing on distributed server

### ISSUE THREAD

**Issue by HuangPZ** [snwagh/falcon-public#30]
Hello!

I was trying to test the code on three machines under LAN. Is changing the IP_LAN and the makefile of choosing LAN setting all I need to do? After doing so, I tried to run make zero/one/two on the three machines but after data loading, no further responses are given and it seems no data are transferred. 

If I'm doing wrong would you mind telling me the right way to do so? Thanks a lot!

**Comment by snwagh** [comment]
Sorry for the delay. Does the network connection get established between the parties? A few things that come to mind: 
- The machines are not connecting (firewall, network settings etc could be the issue here). To debug this, add a simple data exchange/reconstruct function call [here](https://github.com/snwagh/falcon-public/blob/master/src/main.cpp#L50) and see if it succeeds. 
- The code (actual computation so network, dataset etc) running on the 3 machines might not be the same. Reset the repos to the same commit in that case. 
- The IP address are in incorrect orders/not configured on each machine (so the make zero command should correspond to the first party)

Finally, just log debug the control flow and let me know what your main.cpp looks like and where the control flow gets stuck and if there is any error message printed on the terminal.

**Comment by HuangPZ** [comment]
Thx! I think it was the port issue in my machines
