### ISSUE TITLE
Configuring the network of linux server

### ISSUE THREAD

**Issue by HuangPZ** [snwagh/falcon-public#33]
Hi, I was trying to conduct the experiment on Linux servers, but I could not get the results from the paper. For the smaller networks, the computation time is almost ignorable, and the main overhead comes from the transmission. For example, for a network like Sarda, in the WAN setting of 70ms ping time between servers and 40MB/s speed, I spent 2.16s purely in data transmission during inference (counted through adding timers in sendVector and receiveVector, computation cost < 0.05s), while the paper reports only 0.76s in total. One thing I notice is that in my case the time cannot simply match adding the round delay + transmission time, and this is very likely to be caused by the vector being split into several packages and costed several rounds during transmission due to the transmission protocol settings.

Did your experiment specifically set some parameters or rules for the Linux data transmission to perform better in large packages? Would you mind sharing those settings so I can better reproduce the results you have? Of course, if you have some other theory for the difference, please let me know! I'm not using an Amazon server as in the paper, would that potentially caused this kind of huge difference?

Thanks!

**Comment by snwagh** [comment]
It could be the result of the amortization w.r.t the batch. Can you try the batch size provided in the paper and then check the per image inference?

If that's not agreeing, could you paste the output of your runs? And can you confirm you used the exact same set-up as in the paper? Network being the dominant cost is expected behaviour in the WAN setting.
